name: api_client
description: Client for the Compass API.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.9.0
resolution: workspace

dependencies:
  logging: ^1.3.0
  models: ^0.1.0
  shared_preferences: ^2.5.3

dev_dependencies:
  test: ^1.26.3
