name: user_repository
description: Repository that manages the user domain.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.10.0
resolution: workspace

dependencies:
  api_client: ^0.1.0
  models: ^0.1.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.28.0
