name: compass_workspace
publish_to: none

environment:
  sdk: ^3.9.0

workspace:
  - packages/activity_repository
  - packages/api
  - packages/api_client
  - packages/authentication_repository
  - packages/app
  - packages/booking_repository
  - packages/continent_repository
  - packages/destination_repository
  - packages/itinerary_config_repository
  - packages/models
  - packages/user_repository

dependencies:
  equatable: ^2.0.7
  logging: ^1.3.0

dev_dependencies:
  bloc_lint: ^0.3.3
  build_runner: ^2.10.2
  dart_frog_lint: ^0.1.2
  mocktail: ^1.0.4
  test: ^1.25.15
  very_good_analysis: ^10.0.0
