name: api
description: A Dart Frog API for the Compass server.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.9.0
resolution: workspace

dependencies:
  bloc: ^9.0.0
  collection: ^1.19.1
  dart_frog: ^1.2.0
  dart_frog_auth: ^1.2.0
  equatable: ^2.0.7
  meta: ^1.16.0
  models: ^0.1.0

dev_dependencies:
  bloc_test: ^10.0.0
  mocktail: ^1.0.4
  test: ^1.25.15
